name: newsappflutter
description: newsappflutter.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.1
  lint: ^2.3.0
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
